### ISSUE TITLE
Ability to search related projects

### ISSUE THREAD

**Issue by amandaCCF** [codeforkansascity/CommunityKC#42]
Would be great for users to be able to search for related projects. E.g. all garden projects, minor home repair, etc. Maybe this means using tags??

**Comment by lacrone** [comment]
We could do this by creating a sub-category for each project type. For instance, under 'Environment & Energy' we could have subcategories for recycling, community gardens, neighborhood cleanup,etc.

We could also have a completely separate field for tagging, but it would probably get redundant

**Comment by lacrone** [comment]
When you come up with a list of subcategories to add, please add the list here
