### ISSUE TITLE
Additional Project Type categories are showing up 

### ISSUE THREAD

**Issue by amandaCCF** [codeforkansascity/CommunityKC#43]
additional project type categories are displayed in the Project Type dropdown (e.g. arts, energy efficiency, events, etc.). Not sure where these came from and when you select one, no projects are listed.

**Comment by lacrone** [comment]
I added a few in response to previous issue: https://github.com/codeforkansascity/CommunityKC/issues/42

**Comment by lacrone** [comment]
I've changed the Project Type dropdown to display the hierarchy of terms so it's less jumbled now. Please let me know what you think.

**Comment by amandaCCF** [comment]
Yeah, that's better! but when you click on one of the subcategories no projects are displayed.

**Comment by lacrone** [comment]
that's because we haven't assigned any terms to any projects. that will be a manual process

**Comment by amandaCCF** [comment]
Oh! i see. we should probably do more thinking on which sub categories we want and start tagging projects with them. Adding that to Silas's list. :)
