### ISSUE TITLE
Page Numbers in Search

### ISSUE THREAD

**Issue by silasck** [codeforkansascity/CommunityKC#48]
Right now if you go to "View All Projects" you can only flip through the pages of projects by hitting 'next' or 'back.' Can we add a way to search through the pages with a '1 2 3 4 5...' like in the picture below? I think it might be helpful for letting people poke around at projects. 

![page search](https://cloud.githubusercontent.com/assets/18126988/14650273/b3448ec4-0630-11e6-9bf7-7b3ddf6dafb4.png)

**Comment by lacrone** [comment]
Done!
