### ISSUE TITLE
Project Address Vs. Address 

### ISSUE THREAD

**Issue by silasck** [codeforkansascity/CommunityKC#49]
Under 'Location' when adding a project or editing a projected it asks for 'Address' and I've noticed on a few projects that people are listing the address of the contact person instead of the actual site. Can we just change the header so it says "Project Address" to clear that up? Like in the picture below. 
![project address](https://cloud.githubusercontent.com/assets/18126988/14722510/7c1e65e4-07d1-11e6-9206-5d2bfc12a264.png)

**Comment by lacrone** [comment]
Done!
