### ISSUE TITLE
Sub-Categories

### ISSUE THREAD

**Issue by silasck** [codeforkansascity/CommunityKC#52]
Education, Arts, Culture-
1. - Technology
2. - Music

Resource-
1. Food
2. Social service

Capacity Building-
1. Employment
2. Workforce training 
3. Leadership training 
4. Formerly Incarerated Opportunity
5. Mapping

Health/Public Safety-
1. Crime Prevention
2. Healthy living
3. Physical activity

Environment and Energy-
1. Parks
2. Trails

**Comment by lacrone** [comment]
Any subcategories for Economic Development & housing?

**Comment by lacrone** [comment]
Should we keep the category for 'community garden?' There seem to be a lot of those...
