### ISSUE TITLE
Dead/Missing Link

### ISSUE THREAD

**Issue by silasck** [codeforkansascity/CommunityKC#53]
On the FAQ page under 'How Do I Use The Mapping Tool'  there is, I think, suppose to be a hyperlink on the word 'here' where you can download a CommunityKC map guide. 

![dead link](https://cloud.githubusercontent.com/assets/18126988/14994242/647326ac-1134-11e6-8778-edfbbb6c1046.png)
](url)

**Comment by lacrone** [comment]
Interesting. This was copied from the original site, where the link is also missing. This is a question for Amanda - I'm not aware of any communitykc guide but she might be.

**Comment by silasck** [comment]
Amanda says we can just remove that entire line, starting at "For instructions on how..." The guide was a past idea, and is no longer relevant.

**Comment by lacrone** [comment]
Done!
