### ISSUE TITLE
Bottom Color Change

### ISSUE THREAD

**Issue by silasck** [codeforkansascity/CommunityKC#61]
Can we change the bottom part of the page from green to black or white? 
![ejemplo](https://cloud.githubusercontent.com/assets/18126988/16025005/819f3bf0-318a-11e6-8562-76211ce837b6.png)

**Comment by lacrone** [comment]
I changed it last week to a charcoal color that complements colors used elsewhere throughout the site. Look OK to you?

**Comment by silasck** [comment]
I like it!
