### ISSUE TITLE
Would like to search by "community garden"

### ISSUE THREAD

**Issue by zmon** [codeforkansascity/CommunityKC#66]
I was showing the application to a potential new users, and wanted to see the community gardens in her area.

**Comment by zmon** [comment]
We were distracted by the "Map Key" area and did not see the search tool to the right of it.    Suggestions would be:

* Put the word "Search" in large print in that area
* Put the search area just below the menu tabs or just to the right of
* Add a magnifying glass icon to the right of the search fields. 
* Reduce the size of the icon area and balloons

**Comment by silasck** [comment]
Thanks for the feedback Paul! That's helpful information to have.

**Comment by lacrone** [comment]
I've de-emphasized the map key - made it smaller and moved it underneath "Recently added" block. I've also added the label "Browse" next to the search filters. The sitewide search form could still use some styling to make it more prominent
