### ISSUE TITLE
New NRF Project Entries  

### ISSUE THREAD

**Issue by silasck** [codeforkansascity/CommunityKC#69]
@lacrone I just moved the recent NRF grant recipients information into an Excel spread sheet so they can be exported into CommunityKC. Is that best emailed to you, or just attach it here?

**Comment by lacrone** [comment]
Sorry, just saw this - probably best to upload it here for posterity. I can work on it this week.

**Comment by silasck** [comment]
Deal, let me know if they need any tweaking or anything.

Thanks!

Silas Covert-Keefe
Americorps VISTA Volunteer

Community Capital Fund
Funding Neighborhood Investment

3200 Wayne Avenue
Robert J. Mohart Multipurpose Center
Kansas City, Missouri  64109
o: 816.389-8756
c: 971.322.6959
e: silas@ccfkansascity.org<mailto:amanda@ccfkansascity.org>
www.ccfkansascity.org<http://www.ccfkansascity.org/>
